WIN_FEATURES = [
    "SetNo",
    "GameNo",
    "PointNumber",
    "P1GamesWon",
    "P2GamesWon",
    "ServeNumber",
    "RallyCount",
    "rally_missing",
    "rally_bucket_num",
    "is_player_on_serve",
    "service_points_played",
    "service_points_won",
    "pct_service_points_won",
    "return_points_played",
    "return_points_won",
    "pct_return_points_won",
    "first_serve_points_played",
    "first_serve_points_won_cum",
    "pct_first_serve_points_won",
    "second_serve_points_played",
    "second_serve_points_won_cum",
    "pct_second_serve_points_won",
    "last_n_points_won_5",
    "is_game_point",
    "is_break_point",
    "is_game_point_against",
    "score_pressure_index",
    "serve_advantage",
    "first_second_gap",
    "momentum_trend",
]

PATTERN_FEATURES = WIN_FEATURES.copy()